knife4j:
  # 是否生产环境 屏蔽所有资源接口
  production: false

druid:
  monitor: false
# 测试环境不需要
management:
  health:
    redis:
      enabled: false
spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 30s
lock:
  type: mysql