server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/laker?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 30s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
knife4j:
  # 是否生产环境 屏蔽所有资源接口
  production: false
# 测试环境不需要
management:
  health:
    redis:
      enabled: false
  influx:
    metrics:
      export:
        enabled: false
        password: 12345678
        user-name: laker
lock:
  type: mysql
ratelimit:
  type: redis