server:
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  # tomcat配置
  tomcat:
    # 允许最大连接数,默认8192,当达到临界值时,系统会基于accept-count继续接受连接 参数是客户感知型参数。
    max-connections: 8192
    # 当所有线程都在使用时,建立连接的请求的等待队列长度,默认100 请求的backlog值 如果超过max-connections和accept-count总和，新的连接会被拒绝，即直接拒绝服务（直接返回connection refused）
    accept-count: 100
    # 连接器在关闭空闲连接之前等待的毫秒数，默认 20000 20s
    connection-timeout: 20s
    uri-encoding: UTF-8
    threads:
      # 线程池的最小工作线程数,默认10
      min-spare: 50
      # 线程池的最大线程数,默认200
      max: 1000
  servlet:
    context-path: /
spring:
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  profiles:
    active: local
  task:
    execution:
      pool:
        max-size: 10
        queue-capacity: 1
      thread-name-prefix: laker-
  freemarker:
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 20MB
mybatis-plus:
  type-aliases-package: org.snaker.engine.entity
  # 配置日志 #仅控制台输出的日志
  #  configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强
  enable: true
  # 不是很重要的环境，但是又不想暴露文档可以用这个
  basic:
    # 开启basic认证 输入用户名密码才能访问/doc.html
    enable: false
    # 认证用户名
    password: laker
    # 认证密码
    username: laker
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    # 是否开启swagger
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 1.系统模块
      packages-to-scan: com.laker.admin.module.sys
    - group: 2.扩展模块
      packages-to-scan: com.laker.admin.module.ext
    - group: 3.定时任务模块
      packages-to-scan: com.laker.admin.module.task
javamelody:
  # javamelody监控的开关
  enabled: false
  # sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
#  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 1800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结 （例如可以设置为 1800 代表 30 分钟内无操作就冻结
  active-timeout: 1800
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 是否打印操作日志
  is-log: false
  # 是否在初始化配置时在控制台打印版本字符画
  is-print: false
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
easyadmin:
  # web防火墙配置
  waf:
    sql-enabled: false
    xss-enabled: false
    excludes: /flow/*,/sys/nginx/*
  # 文件服务endpoint
  oss-file:
    domain: http://localhost:8080
# actuator
management:
  endpoint:
    health:
      # 生成环境的话注意安全问题
      show-details: always
info:
  author: laker
  version: 1.0.1
